// This import.js is used to easily export the component created in other pages or other component using the Component folder as an import destructuring reference

export { default as PageBody } from "./PageBody/PageBody"
export { default as NavBar} from "./NavBar/NavBar"
export { default as MainHeader} from "./MainHeader/MainHeader"
export { default as ProfileHeader } from "./ProfileHeader/ProfileHeader"
export { default as ProfileButton } from "./ProfileButton/ProfileButton"
export { default as PageNameHeader } from "./PageNameHeader/PageNameHeader"
export { default as MainBody } from "./MainBody/MainBody"
export { default as MainLeftSection } from "./MainLeftSection/MainLeftSection"
export { default as MainRightSection } from "./MainRightSection/MainRightSection"
export { default as MainWelcomeHeader } from "./MainWelcomeHeader/MainWelcomeHeader"
export { default as HomeControls } from "./HomeControls/HomeControls"
export { default as HomeControlButton } from "./HomeControlButton/HomeControlButton"
export { default as CalendarComponent } from "./CalendarComponent/CalendarComponent"
export { default as MainEnrolmentNotification } from "./MainEnrolmentNotification/MainEnrolmentNotification"
export { default as EnrolementCard } from "./EnrolementCard/EnrolementCard"
export { default as IndexLogo} from "./IndexLogo/IndexLogo"
export { default as IndexMiddle } from "./IndexMiddle/IndexMiddle"
export { default as LoginLogo } from "./LoginLogo/LoginLogo"
export { default as LoginText } from "./LoginText/LoginText"
export { default as LoginForm} from "./LoginForm/LoginForm"
export { default as ClassTable } from "./ClasseTable/ClasseTable"
export { default as PlanningTable } from "./PlanningTable/PlanningTable"
export { default as Presences } from "./Presences/Presences"
export { default as CoursTable } from "./CoursTable/CoursTable"
export { default as TableEnrolment } from "./TableEnrolment/TableEnrolment"
export { default as TableAdmin } from "./TableAdmin/TableAdmin"